// Keywords
#define VARS            1
#define PROGRAM         2
#define FUNCTION        3
#define END_FUNCTION    4
#define STARTMAIN       5
#define ENDMAIN         6
#define CLASS           7
#define RETURN          8
#define ARGS            9
#define DELI            10
#define DOT             11
#define TEST            12
#define THEN            13
#define TEST2           14
#define TESTOP          15
#define FOR             16
#define WHILE           17
#define OR              18
#define AND             19
#define LEFT_PAR        20
#define RIGHT_PAR       21
#define LEFT_C_BRA      22
#define RIGHT_C_BRA     23
#define LEFT_BRA        24
#define RIGHT_BRA       25
#define SEM             26
#define COMMA           27
#define CHAR            28
#define BREAK           29
#define INT             30
#define TYPE_COMMENT    31
#define NAME            32
#define OP              33
#define NEWLINE         34
#define INDENT          35
#define ASSIGNOP        36

